### PR TITLE
Adding mysql connector jar to image

### PR DESCRIPTION
**Pull request by dsingh07**
This is useful in the case where lack of outbound access prevents downloading of jar file.

### CODE REVIEW

**Comment by dsingh07** [comment]
After testing with no outbound connectivity, this hasn't worked, will continue investigating and update the PR.

**Comment by dsingh07** [comment]
Pasting the Jar file in the gerrit site folder before initialising the site does not work as Gerrit won't write to a site folder which already has stuff in it, hence container won't go up.

Tried to paste the jar file after initial site initialise, but that also didn't work.

The version of gerrit above our current version does support a "skip download" functionality which would solve our problem https://gerrit-review.googlesource.com/Documentation/pgm-init.html
But no such functionality in current version,

Putting this on hold for now.

**Comment by anton-kasperovich** [comment]
I might didn't get where the actual issue is. I investigated it a little bit and came out with conclusion that it's possible even in current version, just not that convenient as in newest version with argument.

I checked LibraryDownloader file from specifically 2.10 version https://gerrit.googlesource.com/gerrit/+/refs/changes/20/74820/3/gerrit-pgm/src/main/java/com/google/gerrit/pgm/init/LibraryDownloader.java#130 
where you can see that there was already implemented checks.

I've made it with only one difference from your version, i've added instruction directly into Dockerfile:
```
# Add utility scripts
COPY resources/lib/mysql-connector-java-5.1.21.jar ${GERRIT_HOME}/site_ext/lib/mysql-connector-java-5.1.21.jar
COPY resources/scripts/ ${GERRIT_HOME}/adop_scripts/
RUN chmod -R +x ${GERRIT_HOME}/adop_scripts/
```

And if previously it was like this:
```
➜  adop-gerrit git:(master) ✗ docker run --rm -it --network local_network -e DATABASE_TYPE=mysql -e DB_HOSTNAME=adop-gerrit-mysql -e DB_PORT=3306 -e DB_NAME=gerrit -e DB_USER=gerrit -e DB_PASSWORD=gerrit -p 8080:8080 -p 29418:29418 adop-gerrit-debug
First time initialize gerrit...
Generating SSH host key ... rsa(simple)... done
Initialized /var/gerrit/review_site
Upgrading gerrit...
Downloading http://repo2.maven.org/maven2/mysql/mysql-connector-java/5.1.21/mysql-connector-java-5.1.21.jar ... OK
Checksum mysql-connector-java-5.1.21.jar OK
Initialized /var/gerrit/review_site
Upgrading is OK.
Starting gerrit init script
Starting Gerrit...
```

After i implemented this simple change in Dockerfile and copied MySQL Library, now it looks like this:
```
docker run --rm -it --network local_network -e DATABASE_TYPE=mysql -e DB_HOSTNAME=adop-gerrit-mysql -e DB_PORT=3306 -e DB_NAME=gerrit -e DB_USER=gerrit -e DB_PASSWORD=gerrit -p 8080:8080 -p 29418:29418 adop-gerrit-debug
First time initialize gerrit...
Generating SSH host key ... rsa(simple)... done
Initialized /var/gerrit/review_site
Upgrading gerrit...
Initialized /var/gerrit/review_site
Upgrading is OK.
Starting gerrit init script
Starting Gerrit...
nohup: appending output to ‘/var/gerrit/nohup.out’
Running Gerrit Code Review:
[2016-11-23 23:31:42,379] INFO  com.google.gerrit.server.cache.h2.H2CacheFactory : Enabling disk cache /var/gerrit/review_site/cache
[2016-11-23 23:31:43,992] INFO  com.google.gerrit.server.config.ScheduleConfig : gc schedule parameter "gc.interval" is not configured
[2016-11-23 23:31:45,693] INFO  org.eclipse.jetty.util.log : Logging initialized @8304ms
[2016-11-23 23:31:46,035] INFO  com.google.gerrit.server.git.LocalDiskRepositoryManager : Defaulting core.streamFileThreshold to 148m
[2016-11-23 23:31:46,084] INFO  com.google.gerrit.server.plugins.PluginLoader : Loading plugins from /var/gerrit/review_site/plugins
[2016-11-23 23:31:46,772] INFO  com.google.gerrit.sshd.SshDaemon : Started Gerrit SSHD-CORE-0.14.0 on *:29418
[2016-11-23 23:31:46,785] INFO  org.eclipse.jetty.server.Server : jetty-9.2.1.v20140609
[2016-11-23 23:31:48,080] INFO  org.eclipse.jetty.server.handler.ContextHandler : Started o.e.j.s.ServletContextHandler@120283a4{/,file:/var/gerrit/review_site/tmp/gerrit_7068860806304792270_app/gerrit_war/,AVAILABLE}
[2016-11-23 23:31:48,108] INFO  org.eclipse.jetty.server.ServerConnector : Started ServerConnector@5057a3ef{HTTP/1.1}{0.0.0.0:8080}
[2016-11-23 23:31:48,112] INFO  org.eclipse.jetty.server.Server : Started @10726ms
[2016-11-23 23:31:48,115] INFO  com.google.gerrit.pgm.Daemon : Gerrit Code Review 2.10.6 ready
```

Please pay attention that there's no more "Downloading ..."

**Comment by dsingh07** [comment]
Thank you @anton-kasperovich 

That fix has worked. I have tested this out with a built image, and locking down outbound access of my box and works as expected where I get the same output as you.

Ok to be merged from my side.

**Comment by anton-kasperovich** [comment]
Thank you! LGTM.

**Pull request merged**
