### PR TITLE
403 http code included for 'gerrit test connection' and some additional environment variables added

### PR DESCRIPTION
**Pull request by rushan37**
The create_user.sh script has been modified to search for additional http code: 403 during "Testing Gerrit Connection". This is so the script can continue to run if HTTP_LDAP auth is used and http code 401 is not sent.

The JENKINS_PREFIX and GERRIT_PREFIX variables are used to give more flexibility when curling for URLs where the prefix can be modified if used with proxy forwarding.

### CODE REVIEW

**Comment by nickdgriffin** [comment]
Great stuff!

Can you squash your two commits please? Once that's done I'm happy to merge this.

**Comment by nickdgriffin** [comment]
Could you also rebase onto master please as the commit of mine in this tree has been merged?

**Comment by svscorp** [comment]
+1 @rushan37, nice change.

**Comment by nickdgriffin** [comment]
@svscorp When this was tested, did [this line](https://github.com/Accenture/adop-gerrit/pull/3/files#diff-cbcb6ba4d499a6dd35366c0a4857fe4cR143) just cause a warning to be printed if the JAR wasn't present?

**Pull request merged**
